version: '3'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    profiles: ["individual"]
    networks:
      monitoring: null
    restart: always
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    deploy:
      resources:
         limits:
            cpus: '0.500'
            memory: 500M
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    profiles: ["individual"]
    networks:
      monitoring: null
    ports:
      - "6831:6831/udp"
      - "16686:16686"
      # - 5775:5775/udp
      # - 5778:5778
      # - 6832:6832/udp
      # - 9411:9411
      # - 14268:14268

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    profiles: ["grafana", "otlp"]
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      monitoring: null
    volumes:
      - ./docker-compose/config/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "3200"   # tempo
      - "4317"   # otlp grpc
      - "4318"   # otlp http
      - "9411"   # zipkin

  loki:
    image: grafana/loki:latest
    container_name: loki
    profiles: ["grafana", "otlp"]
    networks:
      monitoring: null
    ports:
      - 3100:3100
    restart: on-failure
    volumes:
      - loki:/loki
      - ./docker-compose/config/loki/loki-config.yaml:/etc/loki/loki-config.yaml

    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    profiles: ["grafana", "otlp"]
    networks:
      monitoring: null
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - grafana:/var/lib/grafana
      - ./docker-compose/config/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - loki
      - prometheus
      - tempo

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    profiles: ["individual", "otlp", "grafana"]
    networks:
      monitoring: null
    volumes:
      - prometheus:/prometheus
      - ./docker-compose/config/prometheus/prometheus.individual.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.68.0
    container_name: otel-collector
    profiles: ["otlp", "datadog"]
    command: ["--config=/etc/otel-collector-config.yml"]
    networks:
      monitoring: null
    ports:
      - "4317:4317"
      - "4318:4318"
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension

volumes:
  grafana:
  prometheus:
  promtail:
  loki:
  tempo:

networks:
  monitoring:
    driver: bridge