name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  discussions: write

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - name: Start services 2 and 3
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"
          services: |
            helloworld2
            helloworld3

      - name: Start services 1 too
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose.yml"
          down-flags: "--volumes"

      - name: Start profile 1
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose.yml"
          compose-flags: "--profile profile-1"
          down-flags: "--volumes"

      - name: Start with ENV variables
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/docker-compose-with-env.yml"
        env:
          IMAGE_NAME: hello-world

      - name: Start multiple compose files
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            ./docker/docker-compose.yml
            ./docker/docker-compose.ci.yml
          services: |
            helloworld2
            helloworld4
